'use client';
import {useRef,useState} from 'react';
import type {CoverageCell,EvidenceInput} from '../../../lib/curriculum';
type Release={id:string;unitTitle:string;manifestDigest:string};
const kinds=['rights_attested','expert_review','submitted','correction_requested','correction_resolved','authority_approval','authority_rejection'];
export default function CoveragePanel({report,releases,roles}:{report:{releaseCount:number;applicability:string;approvalNotice:string;cells:CoverageCell[]};releases:Release[];roles:string[]}) {
 const [language,setLanguage]=useState('en'),[level,setLevel]=useState('grade-6'),[selected,setSelected]=useState(releases[0]?.id??''),[events,setEvents]=useState<Record<string,string>[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[requestId,setRequestId]=useState('');
 const historyRequest=useRef(0);
 const canWrite=roles.some(r=>['owner','publisher','content_editor'].includes(r)),authority=roles.some(r=>['owner','publisher'].includes(r));
 async function history(id:string){const token=++historyRequest.current;setSelected(id);setRequestId('');setNotice('');setEvents([]);try{const response=await fetch(`/api/staff/curriculum?release=${encodeURIComponent(id)}`,{cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error);if(token===historyRequest.current)setEvents(value);}catch{if(token===historyRequest.current)setNotice('Evidence history could not be loaded.');}}
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const form=event.currentTarget,fields=new FormData(form),release=releases.find(r=>r.id===selected);if(!release)return;
  const id=requestId||crypto.randomUUID();setRequestId(id);setBusy(true);setNotice('');
  const value:EvidenceInput={id,releaseId:release.id,manifestDigest:release.manifestDigest,kind:String(fields.get('kind')) as EvidenceInput['kind'],reviewer:String(fields.get('reviewer')),reference:String(fields.get('reference')),documentUrl:String(fields.get('url')),documentDigest:String(fields.get('digest')),notes:String(fields.get('notes')),parentEventId:fields.get('parent')?String(fields.get('parent')):null};
  try{const response=await fetch('/api/staff/curriculum',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const body=await response.json();if(!response.ok)throw new Error(body.error);setRequestId('');form.reset();await history(selected);setNotice('Evidence recorded for this exact content digest. Refresh inventory to update counts.');}catch(error){setNotice(error instanceof Error?error.message:'Evidence failed. Retry preserves this request ID.');}finally{setBusy(false);}
 }
 return <>
  <section className="panel"><h2>Coverage inventory</h2><p>{report.releaseCount} releases inspected across the full catalogue. Empty cells remain visible.</p><p className="muted">{report.applicability} {report.approvalNotice}</p>
   <div className="actions"><label>Language<select value={language} onChange={e=>setLanguage(e.target.value)}>{['en','hi','sa','fr','de'].map(v=><option key={v}>{v}</option>)}</select></label><label>Level<select value={level} onChange={e=>setLevel(e.target.value)}>{[...new Set(report.cells.map(c=>c.level))].map(v=><option key={v}>{v}</option>)}</select></label><a href="/api/staff/curriculum" download="keeel-curriculum-coverage.json">Export full reviewer inventory JSON</a></div>
   <div style={{overflowX:'auto'}}><table><thead><tr><th>Skill</th><th>Draft units</th><th>Published units</th><th>Outcome mapped</th><th>Age reviewed</th><th>Approval evidence recorded</th><th>Topic gaps (applicability needs review)</th></tr></thead><tbody>{report.cells.filter(c=>c.language===language&&c.level===level).map(cell=><tr key={cell.skill}><td>{cell.skill}</td><td>{cell.draft}</td><td>{cell.published}</td><td>{cell.mapped}</td><td>{cell.ageReviewed}</td><td>{cell.evidenceRecorded}</td><td>{cell.missingTopics.join(', ')||'All inventory tags present; expert review still required.'}{cell.topics.some(t=>!t.startsWith(`${cell.skill}.`))&&<p>Custom or unmatched topic tags are present; review mapping.</p>}</td></tr>)}</tbody></table></div>
  </section>
  <section className="panel"><h2>Version-bound evidence and correction log</h2><p>Use actual company expert/rights/authority documents. URLs are references; this tool does not verify or download them. Approval evidence does not publish content.</p>
   <label>Content release<select disabled={busy} value={selected} onChange={e=>void history(e.target.value)}>{releases.map(r=><option key={r.id} value={r.id}>{r.unitTitle} · {r.id}</option>)}</select></label><button type="button" disabled={!selected||busy} onClick={()=>void history(selected)}>Load evidence history</button>
   {canWrite&&selected&&<form onSubmit={save} onChange={()=>{if(requestId)setRequestId('');}}><label>Evidence kind<select name="kind" required>{kinds.filter(v=>authority||!v.startsWith('authority_')).map(v=><option key={v}>{v}</option>)}</select></label><label>Expert / authority<input name="reviewer" required maxLength={200}/></label><label>Document / approval reference<input name="reference" required maxLength={500}/></label><label>HTTPS document URL<input name="url" type="url" required maxLength={2000}/></label><label>Document SHA-256<input name="digest" pattern="[a-f0-9]{64}" required maxLength={64}/></label><label>Earlier correction request event ID (required for resolution)<input name="parent" maxLength={36}/></label><label>Notes<textarea name="notes" maxLength={4000}/></label><button disabled={busy}>{busy?'Recording…':'Record evidence'}</button></form>}
   {events.map(event=><article className="panel" key={event.id}><strong>{event.kind}</strong><p>{event.reviewer} · {event.reference}</p><p>Event {event.id} · digest {event.manifestDigest}</p><a href={event.documentUrl} target="_blank" rel="noopener noreferrer">Evidence document reference</a><p>{event.notes}</p></article>)}
   {notice&&<p role="status">{notice}</p>}
  </section>
 </>;
}
