'use client';
import registry from '../../../../../contracts/learning-registry.json';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import ReleaseEditor from './release-editor';
import type {Manifest,Activity} from '../../../lib/package';
type Release={manifestDigest:string;id:string;status:string;manifest:Manifest;publishedAt:string|null;unitTitle:string;courseTitle:string;collectionId:string};
import DemoLibrary from './demo-library';
export default function ContentManager({roles,releases}:{roles:string[];releases:Release[]}){
  const router=useRouter(),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[showCreate,setShowCreate]=useState(false);
  const [confirm,setConfirm]=useState<{id:string;action:'review'|'publish'}|null>(null),[ageAppropriate,setAgeAppropriate]=useState(false);
  const [editing,setEditing]=useState<Release|null>(null),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[conflict,setConflict]=useState(false);
  const [media,setMedia]=useState<Record<string,{url:string;mimeType:string;path:string}[]>>({});
  const edit=roles.some(role=>['owner','content_editor'].includes(role)),publish=roles.some(role=>['owner','publisher'].includes(role));
  const visible=releases.filter(release=>(status==='all'||release.status===status)&&`${release.unitTitle} ${release.courseTitle} ${release.manifest.language}`.toLowerCase().includes(search.toLowerCase()));
  async function send(body:FormData|Record<string,unknown>){
    setBusy(true);setNotice('');setConflict(false);
    try {
      const response=await fetch('/api/staff/content',{method:'POST',...(body instanceof FormData?{body}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});
      const result=await response.json();
      if(!response.ok){if(response.status===409)setConflict(true);throw new Error(result.error??'Request failed');}
      if(!(body instanceof FormData)&&body.action==='preview'){setMedia(previous=>({...previous,[String(body.id)]:result.assets}));return;}
      setEditing(null);setNotice(!(body instanceof FormData)&&body.action==='demo'&&body.demoKey?(result.created===false?'This demonstration is already in the library.':'Demonstration draft added. Review its lessons before publishing.'):'Content action completed.');setConfirm(null);setShowCreate(false);router.refresh();
    }catch(error){setNotice(error instanceof Error?error.message:'Content action failed.');}finally{setBusy(false);}
  }
  function create(event:React.FormEvent<HTMLFormElement>){
    event.preventDefault();const fields=new FormData(event.currentTarget);
    const draft={courseTitle:fields.get('course'),unitTitle:fields.get('unit'),lessonTitle:fields.get('lesson'),language:fields.get('language'),level:fields.get('level'),story:fields.get('story'),question:fields.get('question'),options:String(fields.get('options')).split('\n').filter(value=>value.trim()),correctIndex:Number(fields.get('correct'))-1,demonstration:fields.get('demo')==='on'};
    const body=new FormData();body.set('draft',JSON.stringify(draft));const audio=fields.get('audio');if(audio instanceof File&&audio.size)body.set('audio',audio);void send(body);
  }
  return <>
    {editing&&<ReleaseEditor key={editing.id} manifest={editing.manifest} busy={busy} onCancel={()=>setEditing(null)} onSave={manifest=>void send({action:'save',id:editing.id,expectedDigest:editing.manifestDigest,manifest})}/>}
    <section className="panel"><div className="filters"><label>Filter this page<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Title, course or language"/></label><label>Status<select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All releases</option>{['draft','published','withdrawn'].map(value=><option key={value}>{value}</option>)}</select></label></div><p>{visible.length} of {releases.length} releases on this page.</p></section>
    {notice&&<p className="notice" role="status">{notice}</p>}{conflict&&<button className="secondary" onClick={()=>{setEditing(null);setConflict(false);router.refresh();}}>Discard unsaved edits and reload latest content</button>}
    {edit&&<section className="panel"><h2>Create a unit</h2><p>Start with a reading story and a question. Add interactive activities with Edit lessons. Narration is optional.</p><div className="actions"><button disabled={busy} onClick={()=>setShowCreate(!showCreate)}>{showCreate?'Close new unit':'New unit'}</button></div>
      {showCreate&&<form onSubmit={create}><div className="filters"><div><label>Course title<input name="course" required maxLength={120}/></label><label>Unit title<input name="unit" required maxLength={120}/></label><label>Lesson title<input name="lesson" required maxLength={120}/></label></div><div><label>Language<select name="language">{registry.languages.map(({code,name})=><option key={code} value={code}>{name}</option>)}</select></label><label>Stage, grade or proficiency<select name="level">{Array.from({length:12},(_,index)=><option key={index} value={`grade-${index+1}`}>Grade {index+1}</option>)}{[...registry.stages,...registry.proficiencies].map(level=><option key={level}>{level}</option>)}</select></label><label>Reference narration (optional WAV)<input name="audio" type="file" accept=".wav,audio/wav"/></label></div></div><label>Reading text<textarea name="story" required maxLength={10000} rows={6}/></label><label>Comprehension question<input name="question" required maxLength={500}/></label><label>Answer options (one per line)<textarea name="options" required rows={4}/></label><label>Correct option number<input name="correct" type="number" required min={1} max={8} defaultValue={1}/></label><label className="checkbox-label"><input type="checkbox" name="demo"/>Label as demonstration content</label><button disabled={busy}>Save draft</button></form>}
    </section>}
    {edit&&<DemoLibrary busy={busy} onAdd={key=>void send({action:'demo',demoKey:key})}/>}
    {confirm&&<section className="panel"><h2>{confirm.action==='review'?'Confirm content review':'Publish this unit'}</h2><p>{confirm.action==='review'?'Check the text, media, answers and usage rights for this exact revision.':'The reviewed package becomes immutable and available to every active licensed device.'}</p>{confirm.action==='review'&&<label className="checkbox-label"><input type="checkbox" checked={ageAppropriate} onChange={event=>setAgeAppropriate(event.target.checked)}/>I checked this content for its declared age/level. Staff confirmation does not replace formal curriculum or authority approval.</label>}<div className="actions"><button disabled={busy||(confirm.action==='review'&&!ageAppropriate)} onClick={()=>void send({...confirm,ageAppropriate})}>Confirm {confirm.action}</button><button className="secondary" disabled={busy} onClick={()=>setConfirm(null)}>Cancel</button></div></section>}
    {!releases.length&&<section className="panel"><p>No units yet. Create a draft to get started.</p></section>}
    {visible.map(release=><section className="panel" key={release.id}><div className="section-heading"><h2>{release.unitTitle}</h2><span className="badge">{release.status==='draft'&&release.manifest.publication_status==='reviewed'?'Reviewed draft':release.status}</span></div><p>{release.courseTitle} · {release.manifest.language} · {release.manifest.level} · Version {release.manifest.version}</p><p className="muted">Revisions retain the unit identity; copying creates another unit. Existing published versions and results remain preserved.</p>
      <details><summary>Preview all lessons</summary>{release.manifest.lessons.map(lesson=><article key={lesson.id}><h3>{lesson.title}</h3>{lesson.learning_outcomes?.map(outcome=><p key={outcome}>Outcome: {outcome}</p>)}{lesson.activities.map(activity=><ActivityPreview key={activity.id} activity={activity}/>)}</article>)}{release.manifest.assets.length>0&&(edit||publish)&&<button disabled={busy} className="secondary" onClick={()=>void send({action:'preview',id:release.id})}>Preview attached media</button>}{media[release.id]?.map(asset=><figure key={asset.url}><figcaption>{asset.path}</figcaption>{asset.mimeType.startsWith('image/')?<img src={asset.url} alt={`Content preview: ${asset.path}`} style={{maxWidth:'100%',maxHeight:400}}/>:asset.mimeType.startsWith('video/')?<video controls preload="metadata" src={asset.url} style={{maxWidth:'100%'}}/>:<audio controls preload="none" src={asset.url}/>}</figure>)}<p>{release.manifest.assets.length} media file(s), {release.manifest.assets.reduce((sum,asset)=>sum+asset.byte_size,0)} bytes.</p></details>
      {edit&&<div className="actions"><button className="secondary" disabled={busy} onClick={()=>void send({action:'clone',id:release.id})}>Copy to a new unit</button>{release.status==='draft'&&<button disabled={busy} onClick={()=>setEditing(release)}>Edit lessons</button>}{release.status==='published'&&<button disabled={busy} className="secondary" onClick={()=>void send({action:'revision',id:release.id})}>Create a draft revision</button>}</div>}
      {edit&&release.status==='draft'&&<form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);form.set('action','asset');form.set('id',release.id);form.set('expectedDigest',release.manifestDigest);void send(form);}}><label>Attach media (WAV, PNG, JPEG or MP4, up to 20 MB)<input name="media" type="file" accept=".wav,.png,.jpg,.jpeg,.mp4" required disabled={busy||editing!==null}/></label><p className="muted">Uploading resets review. Container validation does not guarantee playback on every device. For nested pages/cards, asset IDs are available below.</p><details><summary>Attached asset IDs</summary>{release.manifest.assets.map(asset=><p key={asset.id}>{asset.relative_path}: <code>{asset.id}</code></p>)}</details><button disabled={busy||editing!==null}>Attach media</button></form>}
      {publish&&release.status==='draft'&&<div className="actions"><button disabled={busy||release.manifest.publication_status==='reviewed'} onClick={()=>{setAgeAppropriate(false);setConfirm({id:release.id,action:'review'});}}>Mark reviewed</button><button disabled={busy||release.manifest.publication_status!=='reviewed'} onClick={()=>setConfirm({id:release.id,action:'publish'})}>Publish unit</button></div>}
    </section>)}
  </>;
}
function ActivityPreview({activity:a}:{activity:Activity}){
  return <div className="panel"><h4>{a.type.replaceAll('_',' ')}</h4><p>{a.prompt}</p>{a.passage&&<blockquote>{a.passage}</blockquote>}{a.options&&<ol>{a.options.map((option,index)=><li key={index}>{option}{index===a.correct_index||a.correct_indices?.includes(index)?' (correct)':''}</li>)}</ol>}{a.pairs?.map(pair=><p key={pair.id}>{pair.left} → {pair.right}</p>)}{a.segments&&<p>{a.segments.join(' [gap] ')}</p>}{a.answers&&<p>Accepted gaps: {a.answers.map(values=>values.join(' / ')).join('; ')}</p>}{a.accepted_answers&&<p>Accepted answers: {a.accepted_answers.join(' / ')}</p>}{a.correct_order?.map(id=><p key={id}>{a.items?.find(item=>item.id===id)?.text}</p>)}{a.entries?.map(entry=><p key={entry.id}>{entry.term}: {entry.definition} {entry.example}</p>)}{a.pages?.map(page=><p key={page.id}>{page.text} {page.alt_text}</p>)}{a.turns?.map((turn,index)=><p key={index}>{turn.speaker}: {turn.text}</p>)}{a.writing_mode&&<p>Writing: {a.writing_mode}; not automatically scored. {a.starters?.join(' · ')}</p>}{a.alt_text&&<p>Image description: {a.alt_text}</p>}{a.explanation&&<p>Feedback: {a.explanation}</p>}</div>;
}
